//! MMSB Analyzer Library
//!
//! Provides code analysis capabilities for Rust and Julia projects.

#[path = "020_invariant_types.rs"]
pub mod invariant_types;
#[path = "030_refactor_constraints.rs"]
pub mod refactor_constraints;
#[path = "040_scc_compressor.rs"]
pub mod scc_compressor;
#[path = "060_layer_inference.rs"]
pub mod layer_inference;
#[path = "080_fixpoint_solver.rs"]
pub mod fixpoint_solver;
#[path = "100_structural_detector.rs"]
pub mod structural_detector;
#[path = "120_semantic_detector.rs"]
pub mod semantic_detector;
#[path = "140_path_detector.rs"]
pub mod path_detector;
#[path = "150_invariant_integrator.rs"]
pub mod invariant_integrator;
#[path = "170_invariant_reporter.rs"]
pub mod invariant_reporter;
#[path = "180_conscience_graph.rs"]
pub mod conscience_graph;
#[path = "190_action_validator.rs"]
pub mod action_validator;
#[path = "200_agent_conscience.rs"]
pub mod agent_conscience;
#[path = "000_cluster_001.rs"]
pub mod cluster_001;
#[path = "010_cluster_008.rs"]
pub mod cluster_008;
#[path = "050_cluster_010.rs"]
pub mod cluster_010;
#[path = "070_cluster_011.rs"]
pub mod cluster_011;
#[path = "110_cluster_006.rs"]
pub mod cluster_006;
#[path = "090_dependency.rs"]
pub mod dependency;
#[path = "130_layer_core.rs"]
pub mod layer_core;
#[path = "160_layer_utilities.rs"]
pub mod layer_utilities;
#[path = "210_utilities.rs"]
pub mod utilities;
#[path = "220_types.rs"]
pub mod types;
#[path = "230_cohesion_analyzer.rs"]
pub mod cohesion_analyzer;
#[path = "240_directory_analyzer.rs"]
pub mod directory_analyzer;
#[path = "250_control_flow.rs"]
pub mod control_flow;
#[path = "260_file_ordering.rs"]
pub mod file_ordering;
#[path = "270_julia_parser.rs"]
pub mod julia_parser;
#[path = "280_rust_parser.rs"]
pub mod rust_parser;
#[path = "290_dot_exporter.rs"]
pub mod dot_exporter;
#[path = "310_report.rs"]
pub mod report;
#[path = "350_dead_code_types.rs"]
pub mod dead_code_types;
#[path = "211_dead_code_attribute_parser.rs"]
pub mod dead_code_attribute_parser;
#[path = "370_dead_code_doc_comment_parser.rs"]
pub mod dead_code_doc_comment_parser;
#[path = "380_dead_code_call_graph.rs"]
pub mod dead_code_call_graph;
#[path = "390_dead_code_intent.rs"]
pub mod dead_code_intent;
#[path = "400_dead_code_test_boundaries.rs"]
pub mod dead_code_test_boundaries;
#[path = "410_dead_code_entrypoints.rs"]
pub mod dead_code_entrypoints;
#[path = "420_dead_code_classifier.rs"]
pub mod dead_code_classifier;
#[path = "430_dead_code_confidence.rs"]
pub mod dead_code_confidence;
#[path = "440_dead_code_actions.rs"]
pub mod dead_code_actions;
#[path = "460_dead_code_report.rs"]
pub mod dead_code_report;
#[path = "470_dead_code_filter.rs"]
pub mod dead_code_filter;
#[path = "490_dead_code_cli.rs"]
pub mod dead_code_cli;
#[path = "510_dead_code_policy.rs"]
pub mod dead_code_policy;
#[path = "530_dead_code_report_split.rs"]
pub mod dead_code_report_split;
#[path = "450_correction_plan_types.rs"]
pub mod correction_plan_types;
#[path = "480_verification_policy_types.rs"]
pub mod verification_policy_types;
#[path = "500_quality_delta_types.rs"]
pub mod quality_delta_types;
#[path = "520_violation_predictor.rs"]
pub mod violation_predictor;
#[path = "540_tier_classifier.rs"]
pub mod tier_classifier;
#[path = "550_confidence_scorer.rs"]
pub mod confidence_scorer;
#[path = "560_correction_plan_generator.rs"]
pub mod correction_plan_generator;
#[path = "570_verification_scope_planner.rs"]
pub mod verification_scope_planner;
#[path = "580_rollback_criteria_builder.rs"]
pub mod rollback_criteria_builder;
#[path = "590_quality_delta_calculator.rs"]
pub mod quality_delta_calculator;
#[path = "600_action_impact_estimator.rs"]
pub mod action_impact_estimator;
#[path = "610_correction_plan_serializer.rs"]
pub mod correction_plan_serializer;
#[path = "620_verification_policy_emitter.rs"]
pub mod verification_policy_emitter;
#[path = "630_correction_intelligence_report.rs"]
pub mod correction_intelligence_report;

pub use invariant_types::*;
pub use refactor_constraints::*;
pub use action_validator::{AgentAction, ConstraintViolation, ViolationSeverity};
pub use agent_conscience::{ActionPermission, AgentConscience};
pub use conscience_graph::{generate_conscience_map, generate_conscience_stats};
pub use dependency::{
    julia_entry_paths, order_julia_files_by_dependency, order_rust_files_by_dependency, LayerGraph,
    build_file_dependency_graph, analyze_file_ordering,
};
pub use types::AnalysisResult;
pub use cohesion_analyzer::FunctionCohesionAnalyzer;
pub use directory_analyzer::DirectoryAnalyzer;
pub use control_flow::ControlFlowAnalyzer;
pub use file_ordering::{DagCache, parallel_build_file_dag};
pub use julia_parser::JuliaAnalyzer;
pub use rust_parser::RustAnalyzer;
pub use dot_exporter::{export_complete_program_dot, export_program_cfg_to_path};
pub use report::ReportGenerator;
